import numpy as np
import h5py
from sklearn.decomposition import PCA


# ============================================================
# Network Connectivity
# Loads static network structure from the connectivity HDF5 file
# generated by save_connectivity() in data_storage.py.
# All spatial index arithmetic is centralized here so analysis
# objects never need to reimplement it.
#
# Compartment ids are only unique per target population, so all
# compartment accessors take (population_id, comp_id) pairs.
# ============================================================

class NetworkConnectivity:
    def __init__(self, connectivity_path):
        """
        Load and cache static network structure from connectivity file.

        Args:
            connectivity_path:  Path to connectivity HDF5 file generated
                                by save_connectivity() at session start.
        """
        self._path      = connectivity_path
        self._pop_meta  = {}    # {pop_id: {"size": [W,H,Z], "nneu": int}}
        self._comp_meta = {}    # {pop_id: {comp_id: {source, target, k, nsyn, type}}}
        self._inds      = {}    # {pop_id: {comp_id: np.ndarray (nsyn,) target neuron indices}}
        self._indt      = {}    # {pop_id: {comp_id: np.ndarray (nsyn,) source neuron indices}}

        with h5py.File(connectivity_path, 'r') as f:
            # population metadata
            for pid in f["populations"]:
                grp = f[f"populations/{pid}"]
                self._pop_meta[pid] = {
                    "size": list(grp.attrs["size"]),
                    "nneu": int(grp.attrs["nneu"]),
                }
            # compartment metadata and synapse indices
            # nested under target population id to reflect unique (pop_id, comp_id) structure
            for pid in f["compartments"]:
                self._comp_meta[pid] = {}
                self._inds[pid]      = {}
                self._indt[pid]      = {}
                for cid in f[f"compartments/{pid}"]:
                    grp = f[f"compartments/{pid}/{cid}"]
                    self._comp_meta[pid][cid] = {
                        "source": str(grp.attrs["source"]),
                        "target": str(grp.attrs["target"]),
                        "k":      int(grp.attrs["k"]),
                        "nsyn":   int(grp.attrs["nsyn"]),
                        "type":   int(grp.attrs["type"]),
                    }
                    self._inds[pid][cid] = grp["inds"][:]
                    self._indt[pid][cid] = grp["indt"][:]

    # --- Population queries ---

    def population_ids(self):
        """List of all population ids in the network."""
        return list(self._pop_meta.keys())

    def compartment_ids(self, population_id):
        """List of compartment ids targeting a given population."""
        return list(self._comp_meta.get(population_id, {}).keys())

    def all_compartment_ids(self):
        """
        List of all (pop_id, comp_id) pairs across the whole network.
        Use when iterating all compartments without a specific target
        population in mind.
        """
        return [(pid, cid)
                for pid, comps in self._comp_meta.items()
                for cid in comps]

    def population_size(self, population_id):
        """Return [W, H, Z] size of a population."""
        return self._pop_meta[population_id]["size"]

    def population_nneu(self, population_id):
        """Total neuron count for a population."""
        return self._pop_meta[population_id]["nneu"]

    def compartment_meta(self, population_id, comp_id):
        """Return metadata dict for a compartment."""
        return self._comp_meta[population_id][comp_id]

    def compartments_onto(self, population_id):
        """
        Return list of (pop_id, comp_id) pairs that target a given population.
        Since comp_id is only unique per target population, pop_id is always
        population_id here, but the pair form is returned for consistency
        with compartments_from.
        """
        return [(population_id, cid)
                for cid in self._comp_meta.get(population_id, {}).keys()]

    def compartments_from(self, source_population_id):
        """
        Return list of (target_pop_id, comp_id) pairs originating from
        a given source population.
        """
        return [(pid, cid)
                for pid, comps in self._comp_meta.items()
                for cid, meta in comps.items()
                if meta["source"] == source_population_id]

    # --- Spatial index arithmetic ---

    def neuron_index(self, population_id, x, y, z):
        """
        Flat neuron index for position (x, y, z) in a population.
        Matches layout in network.py: idx = x*(H*Z) + y*Z + z
        """
        _, H, Z = self._pop_meta[population_id]["size"]
        return int(x * H * Z + y * Z + z)

    def neuron_xyz(self, population_id, flat_index):
        """
        Inverse of neuron_index. Returns (x, y, z) for a flat neuron index.
        """
        W, H, Z = self._pop_meta[population_id]["size"]
        x =  flat_index // (H * Z)
        y = (flat_index %  (H * Z)) // Z
        z =  flat_index %  Z
        return int(x), int(y), int(z)

    def neurons_at_xy(self, population_id, x, y):
        """
        Flat indices of all neurons at grid position (x, y) across all z.
        """
        _, _, Z = self._pop_meta[population_id]["size"]
        return [self.neuron_index(population_id, x, y, z) for z in range(Z)]

    def all_xyz(self, population_id):
        """
        Array of shape (nneu, 3) with (x, y, z) for every neuron in flat
        index order. Useful for spatial scatter and heatmap plots.
        """
        W, H, Z = self._pop_meta[population_id]["size"]
        xs = np.arange(W).repeat(H * Z)
        ys = np.tile(np.arange(H).repeat(Z), W)
        zs = np.tile(np.arange(Z), W * H)
        return np.stack([xs, ys, zs], axis=1)

    # --- Synapse index queries ---

    def synapse_indices_for_target(self, population_id, comp_id,
                                    target_neuron_idx):
        """
        Indices into the synapse array for all synapses onto a target neuron.
        """
        return np.where(
            self._inds[population_id][comp_id] == target_neuron_idx
        )[0]

    def source_neurons_for_target(self, population_id, comp_id,
                                   target_neuron_idx):
        """
        Source neuron indices for all synapses onto a specific target neuron.
        """
        syn_idx = self.synapse_indices_for_target(
            population_id, comp_id, target_neuron_idx
        )
        return self._indt[population_id][comp_id][syn_idx]

    def target_neurons_for_source(self, population_id, comp_id,
                                   source_neuron_idx):
        """
        Target neuron indices for all synapses from a specific source neuron.
        """
        syn_idx = np.where(
            self._indt[population_id][comp_id] == source_neuron_idx
        )[0]
        return self._inds[population_id][comp_id][syn_idx]

    def inds(self, population_id, comp_id):
        """Target neuron index array for all synapses in a compartment."""
        return self._inds[population_id][comp_id]

    def indt(self, population_id, comp_id):
        """Source neuron index array for all synapses in a compartment."""
        return self._indt[population_id][comp_id]


# ============================================================
# Base Reader
# Shared functionality for StructureReader and RateReader:
# SWMR auto-detection, timestep caching, n_snapshots counting,
# and swmr-aware file open and dataset read helpers.
# ============================================================

class _BaseReader:
    """
    Base class for HDF5 snapshot readers.
    Handles SWMR auto-detection, timestep caching, refresh, and
    swmr-aware dataset reads. Subclasses implement data-specific logic.
    """

    def __init__(self, path, swmr=None):
        """
        Args:
            path:  Path to HDF5 file.
            swmr:  If True, open in SWMR read mode for concurrent access
                   while a simulation is writing. If None (default),
                   auto-detected from whether the file is currently open
                   for writing.
        """
        self._path = path
        if swmr is None:
            swmr = self._detect_swmr(path)
        self._swmr      = swmr
        self._timesteps = self._read_timesteps()

    @staticmethod
    def _detect_swmr(path):
        """
        Try opening the file normally. If that raises OSError the file
        is likely being actively written in SWMR mode — return True.
        """
        try:
            with h5py.File(path, 'r', swmr=False) as f:
                pass
            return False
        except OSError:
            return True

    def _read_timesteps(self):
        """Read and return the full timesteps array from file."""
        with self._open() as f:
            return self._read_dataset(f, "timesteps")

    def _open(self):
        """Open the file with the correct swmr setting."""
        return h5py.File(self._path, 'r', swmr=self._swmr)

    def _read_dataset(self, f, path, slc=None):
        """
        Read a dataset with refresh if in SWMR mode.

        Args:
            f:    Open h5py file handle.
            path: Dataset path string.
            slc:  Slice, index, or None (reads entire dataset).
        """
        dset = f[path]
        if self._swmr:
            dset.id.refresh()
        return dset[slc] if slc is not None else dset[:]

    def refresh(self):
        """
        Re-read the timesteps array to update n_snapshots() for a live file.
        Call this before reading from a file being actively written to get
        the current write position.
        """
        self._timesteps = self._read_timesteps()

    def timesteps(self, start=0, end=None):
        """Simulation timestep values for snapshot indices [start:end]."""
        return self._timesteps[start:end]

    def n_snapshots(self):
        """
        Number of snapshots written — index of first unwritten slot.

        Uses the first zero-valued slot as the sentinel rather than
        counting non-zeros, so that timestep 0 from a fresh network
        start is correctly counted as a written snapshot.
        Call refresh() first when reading a live file.
        """
        written = np.where(self._timesteps == 0)[0]
        if len(written) == 0:
            return len(self._timesteps)  # all slots written
        return int(written[0])


# ============================================================
# Structure Reader
# Reads structural snapshots (weights, amplitudes, dN, dM, band power)
# from the HDF5 file written by HDF5Writer during training.
# Snapshot indices are zero-based positions in the preallocated dataset.
# Compartments are stored under their target population id matching
# the (pop_id, comp_id) canonical form of NetworkConnectivity.
# ============================================================

class StructureReader(_BaseReader):
    def __init__(self, hdf5_path, swmr=None):
        """
        Args:
            hdf5_path:  Path to structural HDF5 file written by HDF5Writer.
            swmr:       SWMR read mode. None = auto-detect.
        """
        super().__init__(hdf5_path, swmr)
        with self._open() as f:
            # build map of {pop_id: {comp_id: [field, ...]}}
            self._fields = {}
            for pop_id in f:
                if pop_id == "timesteps":
                    continue
                self._fields[pop_id] = {}
                for comp_id in f[pop_id]:
                    self._fields[pop_id][comp_id] = list(
                        f[pop_id][comp_id].keys()
                    )

    def available_compartments(self):
        """
        Dict of {pop_id: [comp_id, ...]} for all stored compartments.
        Matches the (pop_id, comp_id) canonical form of NetworkConnectivity.
        """
        return {pid: list(comps.keys())
                for pid, comps in self._fields.items()}

    def all_compartment_ids(self):
        """List of all (pop_id, comp_id) pairs in the structural file."""
        return [(pid, cid)
                for pid, comps in self._fields.items()
                for cid in comps]

    def available_fields(self, pop_id, comp_id):
        """List of stored field names for a compartment."""
        return self._fields[pop_id][comp_id]

    def read_snapshot(self, pop_id, comp_id, field, idx):
        """
        Read a single snapshot of a field for a compartment.

        Args:
            pop_id:   Population id string.
            comp_id:  Compartment id string.
            field:    Field name e.g. "w", "a", "dN", "dM", "band_p_f".
            idx:      Snapshot index. Negative indices count from last
                      written snapshot (not end of preallocated array).

        Returns:
            np.ndarray of shape (nsyn,) for "w", (nneu,) for others.
        """
        if idx < 0:
            idx = self.n_snapshots() + idx
        with self._open() as f:
            return self._read_dataset(f, f"{pop_id}/{comp_id}/{field}", idx)

    def read_timeseries(self, pop_id, comp_id, field, start=0, end=None):
        """
        Read a field across a range of snapshot indices.

        Returns:
            np.ndarray of shape (n_snapshots, ...) where ... is the
            per-snapshot shape of the field.
        """
        if end is None:
            end = self.n_snapshots()
        with self._open() as f:
            return self._read_dataset(f, f"{pop_id}/{comp_id}/{field}",
                                      slice(start, end))

    def read_scalar_timeseries(self, pop_id, comp_id, field,
                                reduction="mean", start=0, end=None):
        """
        Read a field timeseries and reduce across neurons to a scalar
        per snapshot. Useful for convergence plots.

        Args:
            reduction:  "mean", "std", "median", "min", or "max".

        Returns:
            np.ndarray of shape (n_snapshots,).
        """
        data = self.read_timeseries(pop_id, comp_id, field, start, end)
        fn   = {"mean":   np.mean,
                "std":    np.std,
                "median": np.median,
                "min":    np.min,
                "max":    np.max}[reduction]
        return fn(data, axis=1)


# ============================================================
# Rate Reader
# Reads firing rate snapshots from the HDF5 file written by
# RateLogger during training or frozen simulation runs.
# ============================================================

class RateReader(_BaseReader):
    def __init__(self, rate_path, swmr=None):
        """
        Args:
            rate_path:  Path to rate HDF5 file written by RateLogger.
            swmr:       SWMR read mode. None = auto-detect.
        """
        super().__init__(rate_path, swmr)
        with self._open() as f:
            self._pop_ids = [k for k in f.keys() if k != "timesteps"]

    def population_ids(self):
        """List of population ids stored in the rate log."""
        return self._pop_ids

    def read_snapshot(self, population_id, idx):
        """
        Read firing rates for a population at a single snapshot index.

        Args:
            population_id:  Population id string.
            idx:            Snapshot index. Negative counts from last written.

        Returns:
            np.ndarray of shape (nneu,).
        """
        if idx < 0:
            idx = self.n_snapshots() + idx
        with self._open() as f:
            return self._read_dataset(f, population_id, idx)

    def read_timeseries(self, population_id, start=0, end=None):
        """
        Read firing rates for a population across a range of snapshots.

        Returns:
            np.ndarray of shape (n_snapshots, nneu).
        """
        if end is None:
            end = self.n_snapshots()
        with self._open() as f:
            return self._read_dataset(f, population_id, slice(start, end))

    def read_spatial_timeseries(self, population_id, connectivity,
                                 start=0, end=None, z=None):
        """
        Read rates reshaped into spatial layout.

        Args:
            connectivity:  NetworkConnectivity instance for size lookup.
            z:             If int, return single z slice -> (T, W, H).
                           If None, return all z layers -> (T, W, H, Z).
                           If "mean", return mean across z -> (T, W, H).

        Returns:
            np.ndarray of appropriate shape.
        """
        rates   = self.read_timeseries(population_id, start, end)
        W, H, Z = connectivity.population_size(population_id)
        spatial = rates.reshape(-1, W, H, Z)
        if z is None:
            return spatial
        elif z == "mean":
            return spatial.mean(axis=3)
        else:
            return spatial[:, :, :, int(z)]

    def read_scalar_timeseries(self, population_id, reduction="mean",
                                start=0, end=None):
        """
        Read rates and reduce across neurons to a scalar per snapshot.

        Args:
            reduction:  "mean", "std", "median", "min", or "max".

        Returns:
            np.ndarray of shape (n_snapshots,).
        """
        data = self.read_timeseries(population_id, start, end)
        fn   = {"mean":   np.mean,
                "std":    np.std,
                "median": np.median,
                "min":    np.min,
                "max":    np.max}[reduction]
        return fn(data, axis=1)


# ============================================================
# Frozen Rate Analysis
# Computes derived quantities from firing rate recordings,
# typically from a frozen-weight simulation run.
# All methods return plain numpy dicts ready for plot_functions.
# ============================================================

class FrozenRateAnalysis:
    def __init__(self, rate_reader, connectivity):
        """
        Args:
            rate_reader:   RateReader instance.
            connectivity:  NetworkConnectivity instance.
        """
        self.rates = rate_reader
        self.conn  = connectivity

    def pca_trajectory(self, population_id, n_components=3,
                        start=0, end=None):
        """
        Fit PCA on population rate timeseries and return the trajectory
        in the top n_components dimensions.

        Returns dict:
            trajectory:          (T, n_components) projected rates
            explained_variance:  (n_components,) fraction of variance explained
            components:          (n_components, nneu) PCA weight vectors
            timesteps:           (T,) simulation timestep values
        """
        rates = self.rates.read_timeseries(population_id, start, end)
        ts    = self.rates.timesteps(start, end)
        pca   = PCA(n_components=n_components)
        traj  = pca.fit_transform(rates)
        return {
            "trajectory":         traj,
            "explained_variance": pca.explained_variance_ratio_,
            "components":         pca.components_,
            "timesteps":          ts,
        }

    def pca_trajectory_for_neurons(self, population_id, neuron_indices,
                                    n_components=3, start=0, end=None):
        """
        PCA trajectory using only a specified subset of neurons.
        Useful for restricting analysis to a spatial region, z-stack,
        or any arbitrary selection of flat neuron indices.

        Args:
            population_id:   Population id string.
            neuron_indices:  List or array of flat neuron indices to include.
            n_components:    Number of PCA components.
            start, end:      Snapshot index range.

        Returns dict:
            trajectory:          (T, n_components) projected rates
            explained_variance:  (n_components,) fraction of variance explained
            components:          (n_components, n_selected) PCA weight vectors
            timesteps:           (T,)
            neuron_indices:      The neuron indices used (for reference)
        """
        rates        = self.rates.read_timeseries(population_id, start, end)
        rates_subset = rates[:, neuron_indices]
        ts           = self.rates.timesteps(start, end)
        pca          = PCA(n_components=n_components)
        traj         = pca.fit_transform(rates_subset)
        return {
            "trajectory":         traj,
            "explained_variance": pca.explained_variance_ratio_,
            "components":         pca.components_,
            "timesteps":          ts,
            "neuron_indices":     list(neuron_indices),
        }

    def pca_weight_maps(self, population_id, n_components=6,
                         start=0, end=None):
        """
        Fit PCA and return the top n_components weight vectors reshaped
        into spatial maps for visualization.

        Returns dict:
            maps:               (n_components, W, H, Z) spatial weight maps
            explained_variance: (n_components,) fraction of variance explained
            population_size:    [W, H, Z] for use by plot functions
        """
        rates   = self.rates.read_timeseries(population_id, start, end)
        W, H, Z = self.conn.population_size(population_id)
        pca     = PCA(n_components=n_components)
        pca.fit(rates)
        return {
            "maps":               pca.components_.reshape(n_components, W, H, Z),
            "explained_variance": pca.explained_variance_ratio_,
            "population_size":    [W, H, Z],
        }

    def rate_heatmap_frames(self, population_id, start=0, end=None, z="mean"):
        """
        Return spatial rate maps across time for heatmap animation.

        Args:
            z:  int for single z slice, "mean" for mean across z,
                None for all z layers.

        Returns dict:
            frames:     (T, W, H) or (T, W, H, Z) spatial rate maps
            timesteps:  (T,) simulation timestep values
            vmin, vmax: global color scale limits across all frames
        """
        frames = self.rates.read_spatial_timeseries(
            population_id, self.conn, start, end, z=z
        )
        ts = self.rates.timesteps(start, end)
        return {
            "frames":    frames,
            "timesteps": ts,
            "vmin":      float(frames.min()),
            "vmax":      float(frames.max()),
        }

    def rate_histogram_frames(self, population_id, n_bins=50,
                               start=0, end=None):
        """
        Return per-frame rate distributions for histogram animation.
        Bin edges are fixed globally across all frames.

        Returns dict:
            frames:     (T, nneu) raw rates per frame
            bins:       (n_bins+1,) fixed bin edges
            timesteps:  (T,) simulation timestep values
            xlim:       (min, max) fixed axis limits
        """
        rates = self.rates.read_timeseries(population_id, start, end)
        ts    = self.rates.timesteps(start, end)
        bins  = np.linspace(rates.min(), rates.max(), n_bins + 1)
        return {
            "frames":    rates,
            "bins":      bins,
            "timesteps": ts,
            "xlim":      (float(rates.min()), float(rates.max())),
        }


# ============================================================
# Convergence Analysis
# Tracks how well the network's target variables are being met
# across training time using structural snapshots.
# Covers rate targets, E/I balance, band power, and dN/dM drift.
# ============================================================

class ConvergenceAnalysis:
    def __init__(self, structure_reader, connectivity):
        """
        Args:
            structure_reader:  StructureReader instance.
            connectivity:      NetworkConnectivity instance.
        """
        self.struct = structure_reader
        self.conn   = connectivity

    def rate_target_timeseries(self, pop_id, comp_id, start=0, end=None):
        """
        Track mean and std of dN across training as a proxy for whether
        rate homeostasis is actively adjusting. dN is the log-domain
        regularization pressure accumulator — sustained non-zero values
        indicate the weight distribution is being actively reshaped.

        Returns dict:
            dN_mean:    (T,) mean dN across neurons
            dN_std:     (T,) std of dN across neurons
            timesteps:  (T,)
        """
        ts = self.struct.timesteps(start, end)
        return {
            "dN_mean":   self.struct.read_scalar_timeseries(
                             pop_id, comp_id, "dN", "mean", start, end),
            "dN_std":    self.struct.read_scalar_timeseries(
                             pop_id, comp_id, "dN", "std",  start, end),
            "timesteps": ts,
        }

    def amplitude_timeseries(self, pop_id, comp_id, start=0, end=None):
        """
        Track amplitude distribution across training snapshots.

        Returns dict:
            a_mean:     (T,) mean amplitude across neurons
            a_std:      (T,) std of amplitude across neurons
            a_median:   (T,) median amplitude
            timesteps:  (T,)
        """
        ts = self.struct.timesteps(start, end)
        return {
            "a_mean":    self.struct.read_scalar_timeseries(
                             pop_id, comp_id, "a", "mean",   start, end),
            "a_std":     self.struct.read_scalar_timeseries(
                             pop_id, comp_id, "a", "std",    start, end),
            "a_median":  self.struct.read_scalar_timeseries(
                             pop_id, comp_id, "a", "median", start, end),
            "timesteps": ts,
        }

    def dM_timeseries(self, pop_id, comp_id, start=0, end=None):
        """
        Track dM (LTP/LTD balance accumulator) across training.
        dM drifting away from zero indicates systematic LTP or LTD dominance.

        Returns dict:
            dM_mean:    (T,) mean dM across neurons
            dM_std:     (T,) std of dM
            dM_median:  (T,) median dM
            timesteps:  (T,)
        """
        ts = self.struct.timesteps(start, end)
        return {
            "dM_mean":   self.struct.read_scalar_timeseries(
                             pop_id, comp_id, "dM", "mean",   start, end),
            "dM_std":    self.struct.read_scalar_timeseries(
                             pop_id, comp_id, "dM", "std",    start, end),
            "dM_median": self.struct.read_scalar_timeseries(
                             pop_id, comp_id, "dM", "median", start, end),
            "timesteps": ts,
        }

    def band_power_timeseries(self, pop_id, comp_id, start=0, end=None):
        """
        Track relative band power fractions across training for compartments
        with band power amplitude learning (primarily I-I).
        Fractions should sum to 1 — drift indicates oscillatory regime change.

        Returns dict:
            pf_mean:    (T,) mean fast band power fraction
            pm_mean:    (T,) mean mid band power fraction
            ps_mean:    (T,) mean slow band power fraction
            timesteps:  (T,)
        """
        fields = self.struct.available_fields(pop_id, comp_id)
        if not any(f.startswith("band_p") for f in fields):
            raise ValueError(
                f"No band power fields found for ({pop_id}, {comp_id}). "
                f"Available fields: {fields}"
            )
        ts    = self.struct.timesteps(start, end)
        pf    = self.struct.read_timeseries(pop_id, comp_id, "band_p_f", start, end)
        pm    = self.struct.read_timeseries(pop_id, comp_id, "band_p_m", start, end)
        ps    = self.struct.read_timeseries(pop_id, comp_id, "band_p_s", start, end)
        total = pf + pm + ps + 1e-8
        return {
            "pf_mean":   (pf / total).mean(axis=1),
            "pm_mean":   (pm / total).mean(axis=1),
            "ps_mean":   (ps / total).mean(axis=1),
            "timesteps": ts,
        }

    def amplitude_histogram_frames(self, pop_id, comp_id,
                                    n_bins=50, start=0, end=None):
        """
        Return per-snapshot amplitude distributions for histogram animation.
        Bin edges fixed globally so the animation is stable.

        Returns dict:
            frames:     (T, nneu) amplitude values per snapshot
            bins:       (n_bins+1,) fixed bin edges
            timesteps:  (T,)
            xlim:       (min, max) fixed axis limits
        """
        data = self.struct.read_timeseries(pop_id, comp_id, "a", start, end)
        ts   = self.struct.timesteps(start, end)
        bins = np.linspace(data.min(), data.max(), n_bins + 1)
        return {
            "frames":    data,
            "bins":      bins,
            "timesteps": ts,
            "xlim":      (float(data.min()), float(data.max())),
        }


# ============================================================
# Weight Evolution Analysis
# Tracks synaptic weight structure across training snapshots.
# Covers per-neuron weight maps, population distributions,
# and spatial weight evolution at specific grid locations.
# ============================================================

class WeightEvolutionAnalysis:
    def __init__(self, structure_reader, connectivity):
        """
        Args:
            structure_reader:  StructureReader instance.
            connectivity:      NetworkConnectivity instance.
        """
        self.struct = structure_reader
        self.conn   = connectivity

    def weight_histogram_frames(self, pop_id, comp_id,
                                 n_bins=50, start=0, end=None):
        """
        Population weight distribution across training snapshots.
        Bin edges fixed globally for stable animation.

        Returns dict:
            frames:     (T, nsyn) weight values per snapshot
            bins:       (n_bins+1,) fixed bin edges
            timesteps:  (T,)
            xlim:       (min, max) fixed axis limits
        """
        data = self.struct.read_timeseries(pop_id, comp_id, "w", start, end)
        ts   = self.struct.timesteps(start, end)
        bins = np.linspace(data.min(), data.max(), n_bins + 1)
        return {
            "frames":    data,
            "bins":      bins,
            "timesteps": ts,
            "xlim":      (float(data.min()), float(data.max())),
        }

    def _weight_map_for_neuron(self, pop_id, comp_id, nidx, w_all):
        """
        Build weight maps for one target neuron across all T snapshots.
        Vectorized across T using np.add.at on a 2D accumulator.

        Args:
            pop_id:    Target population id.
            comp_id:   Compartment id.
            nidx:      Flat target neuron index.
            w_all:     (T, nsyn) weight array already loaded from disk.

        Returns:
            np.ndarray of shape (T, W_src, H_src).
        """
        meta          = self.conn.compartment_meta(pop_id, comp_id)
        src_id        = meta["source"]
        W_s, H_s, Z_s = self.conn.population_size(src_id)
        T             = w_all.shape[0]

        syn_idx  = self.conn.synapse_indices_for_target(pop_id, comp_id, nidx)
        src_idxs = self.conn.indt(pop_id, comp_id)[syn_idx] % (W_s * H_s)

        # vectorized over T — np.add.at accumulates weights from synapses
        # sharing the same source pixel, giving a proper average map
        wmaps = np.zeros((T, W_s * H_s), dtype=np.float32)
        np.add.at(wmaps, (slice(None), src_idxs), w_all[:, syn_idx])
        return wmaps.reshape(T, W_s, H_s)

    def _source_bounding_box(self, pop_id, comp_id, neuron_indices=None):
        """
        Find the tight bounding box in source (x, y) coordinates covering
        synapse locations for a specific set of target neurons.

        Args:
            pop_id:          Target population id.
            comp_id:         Compartment id.
            neuron_indices:  List of flat target neuron indices to restrict
                             the box to. If None, uses all neurons in the
                             compartment — only meaningful for compartments
                             with small receptive fields.

        Returns dict:
            x_min, x_max:  Inclusive x range of source neuron locations.
            y_min, y_max:  Inclusive y range of source neuron locations.
            src_id:        Source population id.
        """
        meta          = self.conn.compartment_meta(pop_id, comp_id)
        src_id        = meta["source"]
        W_s, H_s, Z_s = self.conn.population_size(src_id)

        if neuron_indices is not None:
            # collect source indices only for the specified target neurons
            src_flat = np.concatenate([
                self.conn.indt(pop_id, comp_id)[
                    self.conn.synapse_indices_for_target(
                        pop_id, comp_id, nidx)
                ]
                for nidx in neuron_indices
            ])
        else:
            src_flat = self.conn.indt(pop_id, comp_id)

        # project to 2D by collapsing z
        src_2d = src_flat % (W_s * H_s)
        xs     = src_2d // H_s
        ys     = src_2d %  H_s

        return {
            "x_min":  int(xs.min()),
            "x_max":  int(xs.max()),
            "y_min":  int(ys.min()),
            "y_max":  int(ys.max()),
            "src_id": src_id,
        }

    def weight_map_at_xy(self, pop_id, comp_id, x, y,
                          start=0, end=None):
        """
        Weight maps for all neurons at grid position (x, y) across all z
        layers, over training time. Each neuron's weights are mapped back
        onto the source population spatial grid for visualization.

        Intended for feedforward compartments where the source population
        has a meaningful spatial layout (e.g. P -> E).

        Returns dict:
            frames:         (T, Z, W_src, H_src) weight maps per snapshot,
                            one spatial map per z layer per timestep.
            timesteps:      (T,)
            neuron_indices: (Z,) flat neuron indices of the z-stack at (x,y).
            src_bbox:       Bounding box computed from synapse source locations
                            of only the z-stack neurons at (x,y). Use with
                            crop="bbox" in plot_weight_map_grid to show only
                            the region containing actual synaptic input.
        """
        z_neurons = self.conn.neurons_at_xy(pop_id, x, y)
        Z         = len(z_neurons)

        # load full weight timeseries once — shared across all z neurons
        w_all = self.struct.read_timeseries(pop_id, comp_id, "w", start, end)
        ts    = self.struct.timesteps(start, end)
        T     = w_all.shape[0]

        meta          = self.conn.compartment_meta(pop_id, comp_id)
        W_s, H_s, Z_s = self.conn.population_size(meta["source"])

        frames = np.zeros((T, Z, W_s, H_s), dtype=np.float32)
        for zi, nidx in enumerate(z_neurons):
            frames[:, zi] = self._weight_map_for_neuron(
                pop_id, comp_id, nidx, w_all
            )

        return {
            "frames":         frames,
            "timesteps":      ts,
            "neuron_indices": z_neurons,
            # bounding box from z-stack neurons only so crop reflects
            # the actual receptive field extent at this x,y location
            "src_bbox":       self._source_bounding_box(
                                  pop_id, comp_id,
                                  neuron_indices=z_neurons),
        }

    def weight_cv_timeseries(self, pop_id, comp_id, start=0, end=None):
        """
        Track per-neuron weight CV (coefficient of variation) across training.
        CV = std(w_i) / mean(w_i) per target neuron, summarized across the
        population. A rising CV indicates increasing weight specialization.

        Relies on synapses being sorted by target neuron index after
        coalescing (torch.sparse_coo_tensor.coalesce() guarantees this),
        which allows reshape to (nneu, k) without explicit index lookup.

        Returns dict:
            cv_mean:    (T,) mean CV across neurons
            cv_std:     (T,) std of CV across neurons
            cv_median:  (T,) median CV
            timesteps:  (T,)
        """
        w_all = self.struct.read_timeseries(pop_id, comp_id, "w", start, end)
        ts    = self.struct.timesteps(start, end)
        k     = self.conn.compartment_meta(pop_id, comp_id)["k"]
        nneu  = self.conn.population_nneu(pop_id)
        T     = w_all.shape[0]

        # reshape valid because coalesce sorts by target neuron index,
        # so synapses are contiguous in blocks of k per target neuron
        w_mat       = w_all.reshape(T, nneu, k)
        mu          = w_mat.mean(axis=2)
        sigma       = w_mat.std(axis=2)
        cv_all      = sigma / (mu + 1e-12)

        return {
            "cv_mean":   cv_all.mean(axis=1),
            "cv_std":    cv_all.std(axis=1),
            "cv_median": np.median(cv_all, axis=1),
            "timesteps": ts,
        }

    def amplitude_heatmap_frames(self, pop_id, comp_id,
                                  start=0, end=None, z="mean"):
        """
        Spatial amplitude maps across training snapshots for heatmap animation.

        Args:
            z:  int for single z slice, "mean" for mean across z,
                None for all z layers -> (T, W, H, Z).

        Returns dict:
            frames:     (T, W, H) or (T, W, H, Z) amplitude maps
            timesteps:  (T,)
            vmin, vmax: global color scale limits
        """
        data      = self.struct.read_timeseries(pop_id, comp_id, "a", start, end)
        ts        = self.struct.timesteps(start, end)
        W, H, Z_n = self.conn.population_size(pop_id)

        spatial = data.reshape(-1, W, H, Z_n)
        if z == "mean":
            frames = spatial.mean(axis=3)
        elif z is None:
            frames = spatial
        else:
            frames = spatial[:, :, :, int(z)]

        return {
            "frames":    frames,
            "timesteps": ts,
            "vmin":      float(frames.min()),
            "vmax":      float(frames.max()),
        }